name: Manual Deploy to Pintata CDN

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install Dependencies
      run: npm ci

    - name: Build Resume Library
      run: ng build resume

    - name: Build Main Application
      run: ng build

    - name: Deploy to IPFS via Pinata
      id: deploy
      uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      with:
        pin-name: 'triforce-resume'
        path: './dist/triforce-resume'
        pinata-api-key: ${{ secrets.PINATA_API_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET_KEY }}
        verbose: true
        remove-old: true

    - name: Output Deployment Information
      run: |
        echo "Deployment complete!"
        echo "IPFS Hash: ${{ steps.deploy.outputs.hash }}"
        echo "Pinata Gateway URL: https://gateway.pinata.cloud/ipfs/${{ steps.deploy.outputs.hash }}"
